/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ohmyquiz;


import javafx.application.Application;
import javafx.stage.Stage;
import org.bson.Document;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        // Kết nối và thao tác với MongoDB ở đây

        primaryStage.setTitle("JavaFX + MongoDB Example");
        primaryStage.show();
    }

    public static void main(String[] args) {
        launch(args);
    }
}