/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ohmyquiz;

import javafx.application.Application;
import javafx.scene.Scene;
import javafx.scene.control.Label;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import java.util.Iterator;

import org.bson.Document;
import com.mongodb.client.MongoCollection;
import com.mongodb.client.MongoDatabase;
import com.mongodb.client.FindIterable;
import com.mongodb.client.MongoClient;
import com.mongodb.client.MongoClients;
import com.mongodb.ConnectionString;
import com.mongodb.MongoClientSettings;

public class App extends Application {

    @Override
    public void start(Stage primaryStage) throws Exception {
        // Tạo kết nối tới MongoDB
        MongoClientSettings settings = MongoClientSettings.builder()
                .applyConnectionString(new ConnectionString("mongodb://localhost:27017"))
                .build();
        MongoClient mongoClient = MongoClients.create(settings);

        // Chọn cơ sở dữ liệu và collection
        MongoDatabase database = mongoClient.getDatabase("OhMyQuiz");
        MongoCollection<Document> collection = database.getCollection("quiz");

        // Tạo giao diện JavaFX
        VBox root = new VBox();
        Scene scene = new Scene(root, 400, 300);

        // Truy vấn dữ liệu và hiển thị trên giao diện
        FindIterable<Document> documents = collection.find();
        Iterator<Document> iterator = documents.iterator();
        while (iterator.hasNext()) {
            Document document = iterator.next();
            String jsonData = document.toJson();
            Label label = new Label(jsonData);
            root.getChildren().add(label);
        }

        primaryStage.setTitle("JavaFX + MongoDB Example");
        primaryStage.setScene(scene);
        primaryStage.show();

        // Đóng kết nối
        mongoClient.close();
    }

    public static void main(String[] args) {
        launch(args);

    }
}